[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.136.4"  # Especifica la versión actual que usas localmente
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

